name: SDK Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SOLANA_VERSION: 1.13.5

jobs:
  build-lint-and-test-sdk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/install-solana
        with:
          solana_version: ${{ env.SOLANA_VERSION }}
      - uses: ./.github/actions/yarn-install-and-verify
        with:
          cache_id: sdk
          working_dir: packages/sdk
